version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: sanyuktadb
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - ola_network

  springboot:
    build: .
    container_name: OI_service
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    networks:
      - ola_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sanyukta-db-rds.cmdlxfdnrfju.ap-south-1.rds.amazonaws.com:5432/sanyukta_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Sanyukta

networks:
  ola_network:
    driver: bridge
